# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 351623a0a147464edd04a097abd1c25befc2f9766dab1215c54a955d8daefaf643de633e3313f18be3a953c99cd49a02fdfc11befe2695037ec0bcd13c33059c

test:
  secret_key_base: 4e5d40c0ea57267ad111f76b5cf5ad1c69bac2791f7371522f0b9354c05c15332b98315f272fb969489b58650387c46aeeca5dc5df75c93f628bc5a67c48756a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
